// <auto-generated>
//     Generated from the canonical domain enums in protocol/messages.rs
//     by mbrc-core/build.rs. Rust is the source of truth; do not edit. The
//     variant name is the FFI string token (ToString() / Enum.TryParse).
// </auto-generated>
namespace MusicBeePlugin.Models
{
    public enum PlayState
    {
        Undefined,
        Stopped,
        Playing,
        Paused
    }

    public enum ShuffleMode
    {
        Off,
        Shuffle,
        AutoDj
    }

    public enum RepeatMode
    {
        Undefined,
        None,
        All,
        One
    }

    public enum LastfmStatus
    {
        Normal,
        Love,
        Ban
    }

    public enum QueueType
    {
        Last,
        Next,
        PlayNow,
        AddAndPlay
    }

}
