//! Code generation for the C# side (Rust is the source of truth):
//!
//! 1. csbindgen emits the C ABI P/Invoke bindings
//!    (`../plugin/Ffi/Generated/NativeBridge.Generated.cs`).
//! 2. A small syn-based generator emits the MessagePack DTO POCOs
//!    (`../plugin/Ffi/Generated/NativeBridgeDtos.Generated.cs`) from the
//!    canonical structs in `protocol/messages.rs` + `ffi/dtos.rs`, so the two
//!    sides of the name-keyed msgpack contract cannot drift.
//!
//! Both outputs are checked in; a CI guard (`git diff --exit-code`) fails if
//! either drifts from the Rust source.

use std::collections::HashSet;
use std::path::{Path, PathBuf};

use syn::{
    Attribute, Expr, Fields, GenericArgument, GenericParam, Item, ItemEnum, ItemStruct, Lit,
    PathArguments, Type, UnOp,
};

const DTO_SOURCES: &[&str] = &["src/protocol/messages.rs", "src/ffi/dtos.rs"];

/// The FFI contract enums (`#[repr(i32)]` in `ffi/types.rs`) mirrored to C#.
const ENUM_SOURCE: &str = "src/ffi/types.rs";

fn main() {
    for f in [
        "src/lib.rs",
        "src/ffi/types.rs",
        "src/ffi/mod.rs",
        "build.rs",
    ] {
        println!("cargo:rerun-if-changed={f}");
    }
    for f in DTO_SOURCES {
        println!("cargo:rerun-if-changed={f}");
    }

    generate_abi_bindings();
    generate_dtos();
    generate_enums();
    generate_domain_enums();
}

fn generate_abi_bindings() {
    let out = PathBuf::from("../plugin/Ffi/Generated/NativeBridge.Generated.cs");

    // csbindgen writes LF unconditionally. Emit to a scratch file in OUT_DIR,
    // then route through write_if_changed so the checked-in file gets the same
    // CRLF-normalized, only-write-on-change treatment as the syn-generated ones
    // (no per-build EOL churn, no spurious mtime bump).
    let scratch = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR set by cargo"))
        .join("NativeBridge.Generated.cs");
    csbindgen::Builder::default()
        .input_extern_file("src/lib.rs")
        .input_extern_file("src/ffi/types.rs")
        .csharp_dll_name("mbrc_core")
        .csharp_namespace("MusicBeePlugin.Ffi.Generated")
        .csharp_class_name("NativeMethods")
        .csharp_entry_point_prefix("")
        .csharp_method_prefix("")
        .csharp_use_function_pointer(false)
        .generate_csharp_file(&scratch)
        .expect("generate NativeBridge.Generated.cs");

    let generated =
        std::fs::read_to_string(&scratch).expect("read the generated NativeBridge bindings");
    write_if_changed(&out, &generated);
}

/// Parse the canonical DTO structs and emit matching C# POCOs.
fn generate_dtos() {
    // First pass across all sources: collect every canonical enum name. A field
    // of an enum type serializes as a variant-name string, so it maps to `string`.
    let mut enums: HashSet<String> = HashSet::new();
    let mut files = Vec::new();
    for src in DTO_SOURCES {
        let text = std::fs::read_to_string(src).unwrap_or_else(|e| panic!("read {src}: {e}"));
        let file = syn::parse_file(&text).unwrap_or_else(|e| panic!("parse {src}: {e}"));
        for item in &file.items {
            if let Item::Enum(e) = item {
                enums.insert(e.ident.to_string());
            }
        }
        files.push(file);
    }

    let mut body = String::new();
    for file in &files {
        for item in &file.items {
            if let Item::Struct(s) = item {
                emit_struct(&mut body, s, &enums);
            }
        }
    }

    let out = format!(
        "// <auto-generated>\n\
         //     Generated from the canonical Rust DTOs (protocol/messages.rs +\n\
         //     ffi/dtos.rs) by mbrc-core/build.rs. Rust is the source of truth;\n\
         //     do not edit. Property names are the MessagePack keys (contractless\n\
         //     resolver) and match the Rust serde field names.\n\
         // </auto-generated>\n\
         using System.Collections.Generic;\n\n\
         namespace MusicBeePlugin.Ffi\n{{\n{body}}}\n"
    );

    let path = Path::new("../plugin/Ffi/Generated/NativeBridgeDtos.Generated.cs");
    write_if_changed(path, &out);
}

/// Mirror every `#[repr(i32)]` enum in `ffi/types.rs` to a C# `enum : int` so the
/// FFI discriminants (QueryType / CommandType / NotificationType / MbrcResult)
/// are never hand-copied on the C# side. The values are the ABI contract; the
/// diff guard fails the build if they drift.
fn generate_enums() {
    let text =
        std::fs::read_to_string(ENUM_SOURCE).unwrap_or_else(|e| panic!("read {ENUM_SOURCE}: {e}"));
    let file = syn::parse_file(&text).unwrap_or_else(|e| panic!("parse {ENUM_SOURCE}: {e}"));

    let mut body = String::new();
    for item in &file.items {
        if let Item::Enum(e) = item {
            if is_repr_i32(&e.attrs) {
                emit_enum(&mut body, e);
            }
        }
    }

    let out = format!(
        "// <auto-generated>\n\
         //     Generated from the `#[repr(i32)]` enums in ffi/types.rs by\n\
         //     mbrc-core/build.rs. Rust is the source of truth; do not edit. The\n\
         //     values are the FFI contract discriminants.\n\
         // </auto-generated>\n\
         namespace MusicBeePlugin.Ffi.Generated\n{{\n{body}}}\n"
    );

    write_if_changed(
        Path::new("../plugin/Ffi/Generated/NativeBridgeEnums.Generated.cs"),
        &out,
    );
}

/// Mirror the canonical domain enums in `protocol/messages.rs` (PlayState,
/// ShuffleMode, RepeatMode, LastfmStatus, QueueType) to C# enums, so the two
/// sides' variant spellings - the FFI string tokens the C# host sends via
/// `ToString()` and parses via `Enum.TryParse` - can't drift. These are plain
/// (non-`#[repr(i32)]`) enums with no discriminants; every `pub enum` in
/// messages.rs is a domain enum, so all are emitted.
fn generate_domain_enums() {
    let src = "src/protocol/messages.rs";
    let text = std::fs::read_to_string(src).unwrap_or_else(|e| panic!("read {src}: {e}"));
    let file = syn::parse_file(&text).unwrap_or_else(|e| panic!("parse {src}: {e}"));

    let mut body = String::new();
    for item in &file.items {
        if let Item::Enum(e) = item {
            emit_plain_enum(&mut body, e);
        }
    }

    let out = format!(
        "// <auto-generated>\n\
         //     Generated from the canonical domain enums in protocol/messages.rs\n\
         //     by mbrc-core/build.rs. Rust is the source of truth; do not edit. The\n\
         //     variant name is the FFI string token (ToString() / Enum.TryParse).\n\
         // </auto-generated>\n\
         namespace MusicBeePlugin.Models\n{{\n{body}}}\n"
    );

    write_if_changed(Path::new("../plugin/Models/DomainEnums.Generated.cs"), &out);
}

/// Emit a C# enum with bare variant names (no discriminants), for the
/// string-serialized domain enums.
fn emit_plain_enum(out: &mut String, e: &ItemEnum) {
    let name = e.ident.to_string();
    out.push_str(&format!("    public enum {name}\n    {{\n"));
    let variants: Vec<String> = e
        .variants
        .iter()
        .map(|v| format!("        {}", v.ident))
        .collect();
    out.push_str(&variants.join(",\n"));
    out.push_str("\n    }\n\n");
}

fn emit_enum(out: &mut String, e: &ItemEnum) {
    let name = e.ident.to_string();
    out.push_str(&format!("    public enum {name}\n    {{\n"));
    for variant in &e.variants {
        let ident = variant.ident.to_string();
        let (_, expr) = variant
            .discriminant
            .as_ref()
            .unwrap_or_else(|| panic!("enum {name}::{ident} must have an explicit discriminant"));
        let value = discriminant_value(expr)
            .unwrap_or_else(|| panic!("enum {name}::{ident} has an unsupported discriminant"));
        out.push_str(&format!("        {ident} = {value},\n"));
    }
    out.push_str("    }\n\n");
}

/// Render an integer enum discriminant (a literal or a negated literal) as C#.
fn discriminant_value(expr: &Expr) -> Option<String> {
    match expr {
        Expr::Lit(lit) => match &lit.lit {
            Lit::Int(i) => Some(i.base10_digits().to_string()),
            _ => None,
        },
        Expr::Unary(u) if matches!(u.op, UnOp::Neg(_)) => {
            discriminant_value(&u.expr).map(|v| format!("-{v}"))
        }
        _ => None,
    }
}

fn is_repr_i32(attrs: &[Attribute]) -> bool {
    let mut found = false;
    for attr in attrs {
        if !attr.path().is_ident("repr") {
            continue;
        }
        let _ = attr.parse_nested_meta(|meta| {
            if meta.path.is_ident("i32") {
                found = true;
            }
            Ok(())
        });
    }
    found
}

fn emit_struct(out: &mut String, s: &ItemStruct, enums: &HashSet<String>) {
    let Fields::Named(fields) = &s.fields else {
        return; // only named-field structs are DTOs
    };
    let camel = has_rename_all_camel(&s.attrs);
    let name = s.ident.to_string();
    let generics = generics_str(s);

    out.push_str(&format!("    public class {name}{generics}\n    {{\n"));
    for field in &fields.named {
        let ident = field.ident.as_ref().expect("named field").to_string();
        let key = match field_serde_rename(&field.attrs) {
            Some(rename) => rename,
            None if camel => to_camel(&ident),
            None => ident,
        };
        let cs_type = map_type(&field.ty, enums);
        out.push_str(&format!(
            "        public {cs_type} {} {{ get; set; }}\n",
            escape_ident(&key)
        ));
    }
    out.push_str("    }\n\n");
}

/// Map a Rust field type to its C# equivalent.
fn map_type(ty: &Type, enums: &HashSet<String>) -> String {
    let Type::Path(tp) = ty else {
        return "object".to_string();
    };
    let seg = tp.path.segments.last().expect("non-empty type path");
    let name = seg.ident.to_string();
    match name.as_str() {
        "String" | "str" => "string".to_string(),
        "i32" => "int".to_string(),
        "i64" => "long".to_string(),
        "u32" => "uint".to_string(),
        "u16" => "ushort".to_string(),
        "u8" => "byte".to_string(),
        "bool" => "bool".to_string(),
        "Vec" => format!("List<{}>", first_type_arg(seg, enums)),
        "Option" => first_type_arg(seg, enums),
        other if enums.contains(other) => "string".to_string(),
        // A generic param (e.g. `T`) or another struct type: use the name as-is.
        other => other.to_string(),
    }
}

fn first_type_arg(seg: &syn::PathSegment, enums: &HashSet<String>) -> String {
    if let PathArguments::AngleBracketed(ab) = &seg.arguments {
        if let Some(GenericArgument::Type(t)) = ab.args.first() {
            return map_type(t, enums);
        }
    }
    "object".to_string()
}

fn generics_str(s: &ItemStruct) -> String {
    let params: Vec<String> = s
        .generics
        .params
        .iter()
        .filter_map(|p| match p {
            GenericParam::Type(t) => Some(t.ident.to_string()),
            _ => None,
        })
        .collect();
    if params.is_empty() {
        String::new()
    } else {
        format!("<{}>", params.join(", "))
    }
}

/// True if the struct carries `#[serde(rename_all = "camelCase")]`.
fn has_rename_all_camel(attrs: &[Attribute]) -> bool {
    let mut camel = false;
    for attr in attrs {
        if !attr.path().is_ident("serde") {
            continue;
        }
        let _ = attr.parse_nested_meta(|meta| {
            if meta.path.is_ident("rename_all") {
                let value: syn::LitStr = meta.value()?.parse()?;
                if value.value() == "camelCase" {
                    camel = true;
                }
            } else if meta.input.peek(syn::Token![=]) {
                // Consume `= <value>` for other keys (default, skip_*) so parsing
                // does not error on leftover tokens.
                let _: syn::Expr = meta.value()?.parse()?;
            }
            Ok(())
        });
    }
    camel
}

/// Extract a field-level `#[serde(rename = "...")]`, if present.
fn field_serde_rename(attrs: &[Attribute]) -> Option<String> {
    let mut renamed = None;
    for attr in attrs {
        if !attr.path().is_ident("serde") {
            continue;
        }
        let _ = attr.parse_nested_meta(|meta| {
            if meta.path.is_ident("rename") {
                let value: syn::LitStr = meta.value()?.parse()?;
                renamed = Some(value.value());
            } else if meta.input.peek(syn::Token![=]) {
                let _: syn::Expr = meta.value()?.parse()?;
            }
            Ok(())
        });
    }
    renamed
}

fn to_camel(snake: &str) -> String {
    let mut out = String::new();
    let mut upper_next = false;
    for ch in snake.chars() {
        if ch == '_' {
            upper_next = true;
        } else if upper_next {
            out.push(ch.to_ascii_uppercase());
            upper_next = false;
        } else {
            out.push(ch);
        }
    }
    out
}

/// C# reserved words (plus `from`, a contextual keyword) that a field name may
/// collide with; escaped with `@` so the property name (= msgpack key) is intact.
const CS_RESERVED: &[&str] = &[
    "from",
    "in",
    "is",
    "as",
    "out",
    "ref",
    "new",
    "base",
    "lock",
    "event",
    "default",
    "params",
    "namespace",
    "class",
    "struct",
    "enum",
    "void",
    "int",
    "long",
    "bool",
    "string",
    "object",
    "for",
    "while",
    "return",
    "public",
    "private",
    "static",
    "using",
];

fn escape_ident(name: &str) -> String {
    if CS_RESERVED.contains(&name) {
        format!("@{name}")
    } else {
        name.to_string()
    }
}

/// Write only when the content changes, so an unchanged build doesn't churn the
/// file's mtime (and the checked-in diff guard stays quiet).
///
/// The output is normalized to CRLF: these are checked-in C# sources and
/// `.gitattributes` marks `*.cs` as `eol=crlf`, so emitting LF would make git
/// report the file modified after every build (working-tree LF vs the CRLF it
/// checks out). Comparing the CRLF form against the on-disk (CRLF) file keeps an
/// unchanged rebuild a true no-op.
fn write_if_changed(path: &Path, content: &str) {
    // Normalize any mix to LF first, then to CRLF, so we never emit `\r\r\n`.
    let crlf = content.replace("\r\n", "\n").replace('\n', "\r\n");
    if let Ok(existing) = std::fs::read_to_string(path) {
        if existing == crlf {
            return;
        }
    }
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent).expect("create the generated-bindings directory");
    }
    std::fs::write(path, &crlf).unwrap_or_else(|e| panic!("write {}: {e}", path.display()));
}
