using System;
using System.IO;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Text;
using MessagePack;
using MessagePack.Resolvers;
using System.Linq;
using MusicBeePlugin.Adapters.Contracts;
using MusicBeePlugin.Enumerations;
using MusicBeePlugin.Infrastructure.Logging.Contracts;
using MusicBeePlugin.Infrastructure.Logging.Implementations;
using MusicBeePlugin.Services.Configuration;
using MusicBeePlugin.Services.Core;
using MusicBeePlugin.Services.Generated;
using MusicBeePlugin.Services.Media;
using MusicBeePlugin.Utilities.Data;

namespace MusicBeePlugin.Services
{
    /// <summary>
    ///     P/Invoke wrapper for the Rust mbrc_core native library.
    ///     FFI signatures (DllImports, MbrcCallbacks layout) live in
    ///     <see cref="NativeMethods"/>, generated by csbindgen from Rust. This class
    ///     handles lifecycle, MessagePack DTOs, and callback implementations that
    ///     bridge Rust queries to C# data providers.
    /// </summary>
    public sealed class NativeBridge : INativeBridge, IDisposable
    {
        // NativeBridge fires several log lines while the Rust core is
        // still booting (DLL preload, mbrc_init result) — PluginLogger
        // routes those through RustLogBridge with a BootstrapLogger
        // fallback, so nothing is lost in the init/shutdown windows.
        private static readonly IPluginLogger Logger = new PluginLogger(typeof(NativeBridge));

        #region FFI Delegate Types

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        private delegate int IntCallbackDelegate();

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        private delegate int IntArgCallbackDelegate(int arg);

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        private delegate int QueryCallbackDelegate(
            int queryType,
            IntPtr paramsBuf,
            uint paramsLen,
            out IntPtr outResultBuf,
            out uint outResultLen);

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        private delegate int CommandCallbackDelegate(
            int commandType,
            IntPtr paramsBuf,
            uint paramsLen,
            out IntPtr outResultBuf,
            out uint outResultLen);

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        private delegate void FreeBufferDelegate(IntPtr buf);

        #endregion

        #region Native Library Preload (kernel32)

        [DllImport("kernel32.dll", SetLastError = true, CharSet = CharSet.Unicode)]
        private static extern IntPtr LoadLibrary(string lpFileName);

        [DllImport("kernel32.dll", SetLastError = true)]
        [return: MarshalAs(UnmanagedType.Bool)]
        private static extern bool FreeLibrary(IntPtr hModule);

        #endregion

        #region Query/Command Type Constants

        // Must match QueryType in mbrc-core/src/ffi/types.rs.
        private const int QueryPlayerState = 1;
        private const int QueryTrackInfo = 2;
        private const int QueryCoverData = 3;
        private const int QueryLyrics = 4;
        private const int QueryPlaylistList = 5;
        private const int QueryNowPlayingList = 6;
        private const int QueryRadioStations = 7;
        private const int QueryOutputDevices = 8;
        private const int QueryLibrarySearchGenre = 9;
        private const int QueryLibrarySearchArtist = 10;
        private const int QueryLibrarySearchAlbum = 11;
        private const int QueryLibrarySearchTitle = 12;
        private const int QueryLibraryBrowseGenres = 13;
        private const int QueryLibraryBrowseArtists = 14;
        private const int QueryLibraryBrowseAlbums = 15;
        private const int QueryLibraryBrowseTracks = 16;
        private const int QueryLibraryGenreArtists = 17;
        private const int QueryLibraryArtistAlbums = 18;
        private const int QueryLibraryAlbumTracks = 19;
        private const int QueryNowPlayingDetails = 20;
        private const int QueryAlbumCover = 21;
        private const int QueryCoverCacheBuildStatus = 22;
        private const int QueryPlaybackPosition = 23;
        private const int QueryAlbumCoverBatch = 24;
        private const int QueryNowPlayingRating = 25;
        private const int QueryNowPlayingLfmRating = 26;
        private const int QueryNowPlayingListOrdered = 27;

        // Must match CommandType in mbrc-core/src/ffi/types.rs.
        private const int CmdSetMute = 1;
        private const int CmdSetShuffle = 2;
        private const int CmdSetRepeat = 3;
        private const int CmdSetScrobble = 4;
        private const int CmdSetAutoDj = 5;
        private const int CmdSetRating = 6;
        private const int CmdSetLfmRating = 7;
        private const int CmdOutputSwitch = 8;
        private const int CmdPlaylistPlay = 9;
        private const int CmdLibraryPlayAll = 10;
        private const int CmdNowPlayingListPlay = 11;
        private const int CmdNowPlayingListMove = 12;
        private const int CmdNowPlayingListRemove = 13;
        private const int CmdNowPlayingListSearch = 14;
        private const int CmdLibraryQueueGenre = 15;
        private const int CmdLibraryQueueArtist = 16;
        private const int CmdLibraryQueueAlbum = 17;
        private const int CmdLibraryQueueTrack = 18;
        private const int CmdNowPlayingQueue = 19;

        #endregion

        #region MessagePack Configuration

        // Contractless resolver: uses property names as keys (no [Key]/[MessagePackObject] needed).
        // This avoids referencing MessagePack.Annotations which causes ILRepack resolution issues.
        private static readonly MessagePackSerializerOptions MsgPackOptions =
            MessagePackSerializerOptions.Standard.WithResolver(ContractlessStandardResolver.Instance);

        #endregion

        private readonly IPlayerDataProvider _player;
        private readonly ITrackDataProvider _track;
        private readonly IPlaylistDataProvider _playlist;
        private readonly ILibraryDataProvider _library;
        private readonly IUserSettings _userSettings;
        private readonly ICoverService _coverService;

        // Pinned delegates to prevent GC collection while Rust holds pointers
        private IntCallbackDelegate _playPauseCallback;
        private IntCallbackDelegate _stopCallback;
        private IntCallbackDelegate _nextCallback;
        private IntCallbackDelegate _previousCallback;
        private IntArgCallbackDelegate _setVolumeCallback;
        private IntArgCallbackDelegate _setPositionCallback;
        private QueryCallbackDelegate _queryDataCallback;
        private CommandCallbackDelegate _executeCommandCallback;
        private FreeBufferDelegate _freeBufferCallback;

        private IntPtr _libraryHandle;
        private bool _initialized;
        private bool _disposed;
        private bool _networkingRunning;

        /// <summary>
        ///     True between successful StartNetworking and StopNetworking calls.
        ///     Used by InfoWindow to render the status badge in the settings UI.
        /// </summary>
        public bool IsNetworkingRunning => _networkingRunning;

        /// <summary>
        ///     Probe the Rust server by attempting a TCP connect to the
        ///     configured port on the loopback interface. Returns true when
        ///     a TCP connection is accepted within ~500 ms. Cheap enough to
        ///     run from the InfoWindow's "verify" button.
        /// </summary>
        public bool VerifyConnection()
        {
            if (!_networkingRunning) return false;
            try
            {
                using (var client = new System.Net.Sockets.TcpClient())
                {
                    var task = client.ConnectAsync("127.0.0.1", (int)_userSettings.ListeningPort);
                    return task.Wait(TimeSpan.FromMilliseconds(500)) && client.Connected;
                }
            }
            catch
            {
                return false;
            }
        }

        /// <summary>
        ///     Creates a new NativeBridge instance with data providers for callback handling.
        /// </summary>
        public NativeBridge(
            IPlayerDataProvider player,
            ITrackDataProvider track,
            IPlaylistDataProvider playlist,
            ILibraryDataProvider library,
            IUserSettings userSettings,
            ICoverService coverService)
        {
            _player = player ?? throw new ArgumentNullException(nameof(player));
            _track = track ?? throw new ArgumentNullException(nameof(track));
            _playlist = playlist ?? throw new ArgumentNullException(nameof(playlist));
            _library = library ?? throw new ArgumentNullException(nameof(library));
            _userSettings = userSettings ?? throw new ArgumentNullException(nameof(userSettings));
            _coverService = coverService ?? throw new ArgumentNullException(nameof(coverService));
            PreloadNativeLibrary();
        }

        /// <summary>
        ///     Initialize the Rust core with callbacks and storage path.
        /// </summary>
        public unsafe void Initialize(string storagePath)
        {
            if (_initialized)
            {
                Logger.Warn("NativeBridge already initialized");
                return;
            }

            try
            {
                // Create and pin callback delegates
                _playPauseCallback = OnPlayPause;
                _stopCallback = OnStop;
                _nextCallback = OnNext;
                _previousCallback = OnPrevious;
                _setVolumeCallback = OnSetVolume;
                _setPositionCallback = OnSetPosition;
                _queryDataCallback = OnQueryData;
                _executeCommandCallback = OnExecuteCommand;
                _freeBufferCallback = OnFreeBuffer;

                var callbacks = new MbrcCallbacks
                {
                    player_play_pause = Marshal.GetFunctionPointerForDelegate(_playPauseCallback).ToPointer(),
                    player_stop = Marshal.GetFunctionPointerForDelegate(_stopCallback).ToPointer(),
                    player_next = Marshal.GetFunctionPointerForDelegate(_nextCallback).ToPointer(),
                    player_previous = Marshal.GetFunctionPointerForDelegate(_previousCallback).ToPointer(),
                    player_set_volume = Marshal.GetFunctionPointerForDelegate(_setVolumeCallback).ToPointer(),
                    player_set_position = Marshal.GetFunctionPointerForDelegate(_setPositionCallback).ToPointer(),
                    query_data = Marshal.GetFunctionPointerForDelegate(_queryDataCallback).ToPointer(),
                    execute_command = Marshal.GetFunctionPointerForDelegate(_executeCommandCallback).ToPointer(),
                    free_buffer = Marshal.GetFunctionPointerForDelegate(_freeBufferCallback).ToPointer(),
                };

                var pathBytes = Encoding.UTF8.GetBytes(storagePath + "\0");
                fixed (byte* pathPtr = pathBytes)
                {
                    var result = NativeMethods.mbrc_initialize(callbacks, pathPtr);
                    if (result == 0)
                    {
                        _initialized = true;
                        Logger.Info("Rust core initialized with storage path: {0}", storagePath);
                    }
                    else
                    {
                        Logger.LogError("Rust core initialization failed (error code: {0})", result);
                    }
                }
            }
            catch (DllNotFoundException ex)
            {
                Logger.LogError(ex, "mbrc_core.dll not found — Rust core will not be available");
            }
            catch (Exception ex)
            {
                Logger.LogError(ex, "Failed to initialize Rust core");
            }
        }

        /// <summary>
        ///     Start the Rust HTTP server. The listening port is read from
        ///     core_settings.json in the storage path passed to Initialize;
        ///     C# WinForms is the only writer of that file.
        /// </summary>
        public void StartNetworking()
        {
            if (!_initialized)
            {
                Logger.Warn("Cannot start networking: Rust core not initialized");
                return;
            }

            try
            {
                var result = NativeMethods.mbrc_start_networking();
                if (result == 0)
                {
                    _networkingRunning = true;
                    Logger.Info("Rust HTTP server starting (port from core_settings.json)");
                }
                else
                {
                    Logger.LogError("Failed to start Rust HTTP server (error code: {0})", result);
                }
            }
            catch (Exception ex)
            {
                Logger.LogError(ex, "Failed to start Rust networking");
            }
        }

        /// <summary>
        ///     Stop the Rust HTTP server.
        /// </summary>
        public void StopNetworking()
        {
            if (!_initialized) return;

            try
            {
                var result = NativeMethods.mbrc_stop_networking();
                _networkingRunning = false;
                if (result == 0)
                    Logger.Info("Rust HTTP server stopped");
                else
                    Logger.Warn("Rust HTTP server stop returned {0}", result);
            }
            catch (Exception ex)
            {
                Logger.LogError(ex, "Failed to stop Rust networking");
            }
        }

        /// <summary>
        ///     Forward a MusicBee notification to the Rust core.
        /// </summary>
        public void HandleNotification(int notificationType)
        {
            if (!_initialized) return;

            try
            {
                NativeMethods.mbrc_handle_notification(notificationType);
            }
            catch (Exception ex)
            {
                Logger.LogError(ex, "Failed to forward notification {0} to Rust core", notificationType);
            }
        }

        public void Dispose()
        {
            if (_disposed) return;
            _disposed = true;

            try
            {
                if (_initialized)
                {
                    NativeMethods.mbrc_shutdown();
                    _initialized = false;
                    Logger.Info("Rust core shut down");
                }
            }
            catch (Exception ex)
            {
                Logger.LogError(ex, "Error during Rust core shutdown");
            }

            if (_libraryHandle != IntPtr.Zero)
            {
                FreeLibrary(_libraryHandle);
                _libraryHandle = IntPtr.Zero;
            }

            // Release pinned delegates
            _playPauseCallback = null;
            _stopCallback = null;
            _nextCallback = null;
            _previousCallback = null;
            _setVolumeCallback = null;
            _setPositionCallback = null;
            _queryDataCallback = null;
            _executeCommandCallback = null;
            _freeBufferCallback = null;
        }

        #region Thin Callback Implementations

        private int OnPlayPause()
        {
            try { return _player.PlayPause() ? 0 : 1; }
            catch (Exception ex) { Logger.LogError(ex, "PlayPause callback error"); return -1; }
        }

        private int OnStop()
        {
            try { return _player.StopPlayback() ? 0 : 1; }
            catch (Exception ex) { Logger.LogError(ex, "Stop callback error"); return -1; }
        }

        private int OnNext()
        {
            try { return _player.PlayNext() ? 0 : 1; }
            catch (Exception ex) { Logger.LogError(ex, "Next callback error"); return -1; }
        }

        private int OnPrevious()
        {
            try { return _player.PlayPrevious() ? 0 : 1; }
            catch (Exception ex) { Logger.LogError(ex, "Previous callback error"); return -1; }
        }

        private int OnSetVolume(int volume)
        {
            try { return _player.SetVolume(volume) ? 0 : 1; }
            catch (Exception ex) { Logger.LogError(ex, "SetVolume callback error"); return -1; }
        }

        private int OnSetPosition(int position)
        {
            try { return _player.SetPosition(position) ? 0 : 1; }
            catch (Exception ex) { Logger.LogError(ex, "SetPosition callback error"); return -1; }
        }

        #endregion

        #region Fat Callback Implementations

        private int OnQueryData(int queryType, IntPtr paramsBuf, uint paramsLen,
            out IntPtr outResultBuf, out uint outResultLen)
        {
            outResultBuf = IntPtr.Zero;
            outResultLen = 0;

            try
            {
                byte[] resultBytes;

                switch (queryType)
                {
                    case QueryPlayerState:
                        resultBytes = SerializePlayerState();
                        break;
                    case QueryTrackInfo:
                        resultBytes = SerializeTrackInfo();
                        break;
                    case QueryCoverData:
                        resultBytes = SerializeCoverData();
                        break;
                    case QueryLyrics:
                        resultBytes = SerializeLyrics();
                        break;
                    case QueryPlaylistList:
                        resultBytes = SerializePlaylistList();
                        break;
                    case QueryNowPlayingList:
                        resultBytes = SerializeNowPlayingList(paramsBuf, paramsLen);
                        break;
                    case QueryRadioStations:
                        resultBytes = SerializeRadioStations(paramsBuf, paramsLen);
                        break;
                    case QueryOutputDevices:
                        resultBytes = SerializeOutputDevices();
                        break;
                    case QueryLibrarySearchGenre:
                        resultBytes = SerializeGenreSearch(paramsBuf, paramsLen);
                        break;
                    case QueryLibrarySearchArtist:
                        resultBytes = SerializeArtistSearch(paramsBuf, paramsLen);
                        break;
                    case QueryLibrarySearchAlbum:
                        resultBytes = SerializeAlbumSearch(paramsBuf, paramsLen);
                        break;
                    case QueryLibrarySearchTitle:
                        resultBytes = SerializeTrackSearch(paramsBuf, paramsLen);
                        break;
                    case QueryLibraryBrowseGenres:
                        resultBytes = SerializeGenreBrowse(paramsBuf, paramsLen);
                        break;
                    case QueryLibraryBrowseArtists:
                        resultBytes = SerializeArtistBrowse(paramsBuf, paramsLen);
                        break;
                    case QueryLibraryBrowseAlbums:
                        resultBytes = SerializeAlbumBrowse(paramsBuf, paramsLen);
                        break;
                    case QueryLibraryBrowseTracks:
                        resultBytes = SerializeTrackBrowse(paramsBuf, paramsLen);
                        break;
                    case QueryLibraryGenreArtists:
                        resultBytes = SerializeGenreArtists(paramsBuf, paramsLen);
                        break;
                    case QueryLibraryArtistAlbums:
                        resultBytes = SerializeArtistAlbums(paramsBuf, paramsLen);
                        break;
                    case QueryLibraryAlbumTracks:
                        resultBytes = SerializeAlbumTracks(paramsBuf, paramsLen);
                        break;
                    case QueryNowPlayingDetails:
                        resultBytes = SerializeNowPlayingDetails();
                        break;
                    case QueryAlbumCover:
                        resultBytes = SerializeAlbumCover(paramsBuf, paramsLen);
                        break;
                    case QueryCoverCacheBuildStatus:
                        resultBytes = SerializeCoverCacheBuildStatus();
                        break;
                    case QueryPlaybackPosition:
                        resultBytes = SerializePlaybackPosition();
                        break;
                    case QueryAlbumCoverBatch:
                        resultBytes = SerializeAlbumCoverBatch(paramsBuf, paramsLen);
                        break;
                    case QueryNowPlayingRating:
                        resultBytes = SerializeNowPlayingRating();
                        break;
                    case QueryNowPlayingLfmRating:
                        resultBytes = SerializeNowPlayingLfmRating();
                        break;
                    case QueryNowPlayingListOrdered:
                        resultBytes = SerializeNowPlayingListOrdered(paramsBuf, paramsLen);
                        break;
                    default:
                        Logger.Warn("Unknown query type: {0}", queryType);
                        return -1;
                }

                outResultBuf = Marshal.AllocHGlobal(resultBytes.Length);
                Marshal.Copy(resultBytes, 0, outResultBuf, resultBytes.Length);
                outResultLen = (uint)resultBytes.Length;

                return 0;
            }
            catch (Exception ex)
            {
                Logger.LogError(ex, "Query callback error for type {0}", queryType);
                return -1;
            }
        }

        private int OnExecuteCommand(int commandType, IntPtr paramsBuf, uint paramsLen,
            out IntPtr outResultBuf, out uint outResultLen)
        {
            outResultBuf = IntPtr.Zero;
            outResultLen = 0;

            try
            {
                switch (commandType)
                {
                    case CmdSetMute:
                        return ApplyBool(paramsBuf, paramsLen, _player.SetMute);
                    case CmdSetShuffle:
                        return ApplyBool(paramsBuf, paramsLen, _player.SetShuffle);
                    case CmdSetScrobble:
                        return ApplyBool(paramsBuf, paramsLen, _player.SetScrobble);
                    case CmdSetAutoDj:
                        return ApplyBool(paramsBuf, paramsLen, _player.SetAutoDj);
                    case CmdSetRepeat:
                        return ApplyRepeat(paramsBuf, paramsLen);
                    case CmdSetRating:
                        return ApplySetRating(paramsBuf, paramsLen);
                    case CmdSetLfmRating:
                        return ApplySetLfmRating(paramsBuf, paramsLen);
                    case CmdOutputSwitch:
                        return ApplyStringSetter(paramsBuf, paramsLen, _player.SetOutputDevice);
                    case CmdPlaylistPlay:
                        return ApplyStringSetter(paramsBuf, paramsLen, _playlist.PlayPlaylist);
                    case CmdLibraryPlayAll:
                        return ApplyBool(paramsBuf, paramsLen, _playlist.PlayAllLibrary);
                    case CmdNowPlayingListPlay:
                        return ApplyStringSetter(paramsBuf, paramsLen, _playlist.PlayNowPlayingTrack);
                    case CmdNowPlayingListMove:
                        return ApplyMove(paramsBuf, paramsLen);
                    case CmdNowPlayingListRemove:
                        return ApplyRemoveIndex(paramsBuf, paramsLen);
                    case CmdNowPlayingListSearch:
                        return ApplyNowPlayingSearch(paramsBuf, paramsLen);
                    case CmdLibraryQueueGenre:
                        return ApplyLibraryQueue(paramsBuf, paramsLen, MetaTag.Genre);
                    case CmdLibraryQueueArtist:
                        return ApplyLibraryQueue(paramsBuf, paramsLen, MetaTag.Artist);
                    case CmdLibraryQueueAlbum:
                        return ApplyLibraryQueue(paramsBuf, paramsLen, MetaTag.Album);
                    case CmdLibraryQueueTrack:
                        return ApplyLibraryQueue(paramsBuf, paramsLen, MetaTag.Title);
                    case CmdNowPlayingQueue:
                        return ApplyNowPlayingQueue(paramsBuf, paramsLen);
                    default:
                        Logger.Warn("Unknown command type: {0}", commandType);
                        return -1;
                }
            }
            catch (Exception ex)
            {
                Logger.LogError(ex, "Command callback error for type {0}", commandType);
                return -1;
            }
        }

        private static byte[] CopyParams(IntPtr paramsBuf, uint paramsLen)
        {
            if (paramsBuf == IntPtr.Zero || paramsLen == 0)
                return new byte[0];
            var buf = new byte[paramsLen];
            Marshal.Copy(paramsBuf, buf, 0, (int)paramsLen);
            return buf;
        }

        private static int ApplyBool(IntPtr paramsBuf, uint paramsLen, Func<bool, bool> setter)
        {
            var dto = MessagePackSerializer.Deserialize<SetBoolParams>(
                CopyParams(paramsBuf, paramsLen), MsgPackOptions);
            return setter(dto.value) ? 0 : 1;
        }

        private int ApplyRepeat(IntPtr paramsBuf, uint paramsLen)
        {
            var dto = MessagePackSerializer.Deserialize<SetRepeatParams>(
                CopyParams(paramsBuf, paramsLen), MsgPackOptions);
            if (!Enum.TryParse<Enumerations.RepeatMode>(dto.mode, out var mode))
            {
                Logger.Warn("Invalid repeat mode '{0}'", dto.mode ?? "<null>");
                return 1;
            }
            return _player.SetRepeatMode(mode) ? 0 : 1;
        }

        private static int ApplyStringSetter(IntPtr paramsBuf, uint paramsLen, Func<string, bool> setter)
        {
            var dto = MessagePackSerializer.Deserialize<StringValueParams>(
                CopyParams(paramsBuf, paramsLen), MsgPackOptions);
            return setter(dto.value ?? string.Empty) ? 0 : 1;
        }

        private int ApplySetRating(IntPtr paramsBuf, uint paramsLen)
        {
            var dto = MessagePackSerializer.Deserialize<StringValueParams>(
                CopyParams(paramsBuf, paramsLen), MsgPackOptions);
            return _track.SetNowPlayingRating(dto.value ?? string.Empty) ? 0 : 1;
        }

        private int ApplySetLfmRating(IntPtr paramsBuf, uint paramsLen)
        {
            var dto = MessagePackSerializer.Deserialize<SetLfmRatingParams>(
                CopyParams(paramsBuf, paramsLen), MsgPackOptions);
            if (!Enum.TryParse<LastfmStatus>(dto.status, out var status))
            {
                Logger.Warn("Invalid lfm status '{0}'", dto.status ?? "<null>");
                return 1;
            }
            return _track.SetNowPlayingLastfmStatus(status) ? 0 : 1;
        }

        private int ApplyMove(IntPtr paramsBuf, uint paramsLen)
        {
            var dto = MessagePackSerializer.Deserialize<MoveParams>(
                CopyParams(paramsBuf, paramsLen), MsgPackOptions);
            if (dto.from < 0 || dto.to < 0)
                return 1;
            return _playlist.MoveNowPlayingTrack(dto.from, dto.to) ? 0 : 1;
        }

        private int ApplyRemoveIndex(IntPtr paramsBuf, uint paramsLen)
        {
            var dto = MessagePackSerializer.Deserialize<IndexParams>(
                CopyParams(paramsBuf, paramsLen), MsgPackOptions);
            if (dto.index < 0)
                return 1;
            return _playlist.RemoveFromNowPlayingList(dto.index) ? 0 : 1;
        }

        private int ApplyNowPlayingSearch(IntPtr paramsBuf, uint paramsLen)
        {
            var dto = MessagePackSerializer.Deserialize<StringValueParams>(
                CopyParams(paramsBuf, paramsLen), MsgPackOptions);
            var query = dto.value ?? string.Empty;
            if (string.IsNullOrWhiteSpace(query))
                return 1;

            var source = SearchSourceHelper.GetSearchSource(_userSettings);
            var match = _track.SearchNowPlayingList(query, source);
            if (string.IsNullOrEmpty(match))
                return 1;
            return _playlist.PlayNowPlayingTrack(match) ? 0 : 1;
        }

        private int ApplyLibraryQueue(IntPtr paramsBuf, uint paramsLen, MetaTag metaTag)
        {
            var dto = MessagePackSerializer.Deserialize<LibraryQueueParams>(
                CopyParams(paramsBuf, paramsLen), MsgPackOptions);
            var queueType = MapQueueType(dto.queue_type);
            var query = dto.query ?? string.Empty;
            var source = SearchSourceHelper.GetSearchSource(_userSettings);

            // Title + PlayNow short-circuits the library lookup: `query` is
            // already a file URL produced by librarysearchtitle.
            var fileUrls = metaTag == MetaTag.Title && queueType == QueueType.PlayNow
                ? new[] { query }
                : _library.GetFileUrlsByMetaTag(metaTag, query, source);

            var playFirst = fileUrls != null && fileUrls.Length > 0 ? fileUrls[0] : null;
            return _playlist.QueueFiles(queueType, fileUrls ?? new string[0], playFirst) ? 0 : 1;
        }

        private int ApplyNowPlayingQueue(IntPtr paramsBuf, uint paramsLen)
        {
            var dto = MessagePackSerializer.Deserialize<NowPlayingQueueParams>(
                CopyParams(paramsBuf, paramsLen), MsgPackOptions);
            var files = dto.files ?? new string[0];
            if (files.Length == 0)
                return 1;
            var queueType = MapQueueType(dto.queue_type ?? string.Empty);
            var play = string.IsNullOrEmpty(dto.play) ? null : dto.play;
            return _playlist.QueueFiles(queueType, files, play) ? 0 : 1;
        }

        private static QueueType MapQueueType(string token)
        {
            // Mirrors core/Utilities/Mapping/QueueTypeMapper (which is
            // internal, so we can't reference it from this assembly).
            switch (token)
            {
                case "next": return QueueType.Next;
                case "last": return QueueType.Last;
                case "now": return QueueType.PlayNow;
                case "add-all": return QueueType.AddAndPlay;
                default: return QueueType.Next;
            }
        }

        private void OnFreeBuffer(IntPtr buf)
        {
            if (buf != IntPtr.Zero)
                Marshal.FreeHGlobal(buf);
        }

        #endregion

        #region Serialization Helpers

        private byte[] SerializePlayerState()
        {
            var dto = new PlayerStateDto
            {
                play_state = _player.GetPlayState().ToString(),
                volume = _player.GetVolume(),
                mute = _player.GetMute(),
                shuffle = _player.GetShuffleState().ToString(),
                repeat = _player.GetRepeatMode().ToString(),
                position = _player.GetPosition(),
                scrobble = _player.GetScrobbleEnabled(),
            };
            return MessagePackSerializer.Serialize(dto, MsgPackOptions);
        }

        private byte[] SerializeTrackInfo()
        {
            var track = _track.GetNowPlayingTrackInfo();
            var dto = new TrackInfoDto
            {
                artist = track.Artist ?? string.Empty,
                title = track.Title ?? string.Empty,
                album = track.Album ?? string.Empty,
                year = track.Year ?? string.Empty,
                path = track.Path ?? string.Empty,
            };
            return MessagePackSerializer.Serialize(dto, MsgPackOptions);
        }

        private byte[] SerializeCoverData()
        {
            // Match legacy `Broadcaster.BroadcastCover` fallback chain:
            // embedded artwork first, then MusicBee's downloaded artwork.
            // Going through CoverService keeps that policy in one place.
            var artwork = _coverService.GetNowPlayingCover() ?? string.Empty;
            return MessagePackSerializer.Serialize(artwork, MsgPackOptions);
        }

        private byte[] SerializeLyrics()
        {
            var lyrics = _track.GetNowPlayingLyrics() ?? string.Empty;
            return MessagePackSerializer.Serialize(lyrics, MsgPackOptions);
        }

        private byte[] SerializeNowPlayingRating()
        {
            var rating = _track.GetNowPlayingRating() ?? string.Empty;
            return MessagePackSerializer.Serialize(rating, MsgPackOptions);
        }

        private byte[] SerializeNowPlayingLfmRating()
        {
            // ITrackDataProvider returns the typed enum; the wire wants the
            // PascalCase name (Normal/Love/Ban) just like the legacy
            // protocol. ToString() gives that without an extra mapping.
            var status = _track.GetNowPlayingLastfmStatus().ToString();
            return MessagePackSerializer.Serialize(status, MsgPackOptions);
        }

        private byte[] SerializePlaylistList()
        {
            var playlists = _playlist.GetPlaylists() ?? System.Linq.Enumerable.Empty<Models.Entities.Playlist>();
            var list = new System.Collections.Generic.List<PlaylistDto>();
            foreach (var p in playlists)
                list.Add(new PlaylistDto { url = p.Url ?? string.Empty, name = p.Name ?? string.Empty });
            var dto = new PlaylistListResponse { playlists = list };
            return MessagePackSerializer.Serialize(dto, MsgPackOptions);
        }

        private byte[] SerializeNowPlayingList(IntPtr paramsBuf, uint paramsLen)
        {
            var p = MessagePackSerializer.Deserialize<PaginationParams>(
                CopyParams(paramsBuf, paramsLen), MsgPackOptions);
            return SerializeNowPlayingListEntries(_track.GetNowPlayingListPage(p.offset, p.limit));
        }

        // iOS-v4 variant — queue-absolute position + populated album fields.
        // Routed by the Rust legacy dispatcher when the connection's
        // ClientPlatform == Ios. Captured iOS-v4 fixture frames show
        // {"position": <queue_index>, "album": "...", "album_artist": "..."}
        // which only this enumeration produces.
        private byte[] SerializeNowPlayingListOrdered(IntPtr paramsBuf, uint paramsLen)
        {
            var p = MessagePackSerializer.Deserialize<PaginationParams>(
                CopyParams(paramsBuf, paramsLen), MsgPackOptions);
            return SerializeNowPlayingListEntries(_track.GetNowPlayingListOrdered(p.offset, p.limit));
        }

        private byte[] SerializeNowPlayingListEntries(System.Collections.Generic.IEnumerable<Models.Entities.NowPlaying> page)
        {
            page = page ?? System.Linq.Enumerable.Empty<Models.Entities.NowPlaying>();
            var list = new System.Collections.Generic.List<NowPlayingTrackDto>();
            foreach (var t in page)
                list.Add(new NowPlayingTrackDto
                {
                    artist = t.Artist ?? string.Empty,
                    album = t.Album ?? string.Empty,
                    album_artist = t.AlbumArtist ?? string.Empty,
                    title = t.Title ?? string.Empty,
                    path = t.Path ?? string.Empty,
                    position = t.Position,
                });
            var dto = new NowPlayingListResponse { tracks = list };
            return MessagePackSerializer.Serialize(dto, MsgPackOptions);
        }

        private byte[] SerializeRadioStations(IntPtr paramsBuf, uint paramsLen)
        {
            var p = MessagePackSerializer.Deserialize<PaginationParams>(
                CopyParams(paramsBuf, paramsLen), MsgPackOptions);
            var stations = _library.GetRadioStations(p.offset, p.limit)
                ?? new System.Collections.Generic.List<Models.Entities.RadioStation>();
            var list = new System.Collections.Generic.List<RadioStationDto>();
            foreach (var s in stations)
                list.Add(new RadioStationDto { name = s.Name ?? string.Empty, url = s.Url ?? string.Empty });
            var dto = new RadioStationsResponse { stations = list };
            return MessagePackSerializer.Serialize(dto, MsgPackOptions);
        }

        private byte[] SerializeOutputDevices()
        {
            var od = _player.GetOutputDevices();
            var dto = new OutputDevicesResponse
            {
                active = od?.ActiveDeviceName ?? string.Empty,
                devices = od?.DeviceNames ?? new string[0],
            };
            return MessagePackSerializer.Serialize(dto, MsgPackOptions);
        }

        private System.Collections.Generic.List<GenreDto> ToGenreList(
            System.Collections.Generic.IEnumerable<Models.Entities.GenreData> items)
        {
            var list = new System.Collections.Generic.List<GenreDto>();
            if (items == null) return list;
            foreach (var g in items)
                list.Add(new GenreDto { genre = g.Genre ?? string.Empty, count = g.Count });
            return list;
        }

        private System.Collections.Generic.List<ArtistDto> ToArtistList(
            System.Collections.Generic.IEnumerable<Models.Entities.ArtistData> items)
        {
            var list = new System.Collections.Generic.List<ArtistDto>();
            if (items == null) return list;
            foreach (var a in items)
                list.Add(new ArtistDto { artist = a.Artist ?? string.Empty, count = a.Count });
            return list;
        }

        private System.Collections.Generic.List<AlbumDto> ToAlbumList(
            System.Collections.Generic.IEnumerable<Models.Entities.AlbumData> items)
        {
            var list = new System.Collections.Generic.List<AlbumDto>();
            if (items == null) return list;
            foreach (var a in items)
                list.Add(new AlbumDto
                {
                    artist = a.Artist ?? string.Empty,
                    album = a.Album ?? string.Empty,
                    count = a.TrackCount,
                });
            return list;
        }

        private System.Collections.Generic.List<TrackDto> ToTrackList(
            System.Collections.Generic.IEnumerable<Models.Entities.Track> items)
        {
            var list = new System.Collections.Generic.List<TrackDto>();
            if (items == null) return list;
            foreach (var t in items)
                list.Add(new TrackDto
                {
                    src = t.Src ?? string.Empty,
                    artist = t.Artist ?? string.Empty,
                    title = t.Title ?? string.Empty,
                    trackno = t.TrackNo,
                    disc = t.Disc,
                    album = t.Album ?? string.Empty,
                    album_artist = t.AlbumArtist ?? string.Empty,
                    genre = t.Genre ?? string.Empty,
                });
            return list;
        }

        private QueryParams ReadQuery(IntPtr paramsBuf, uint paramsLen) =>
            MessagePackSerializer.Deserialize<QueryParams>(CopyParams(paramsBuf, paramsLen), MsgPackOptions);

        private BrowseParams ReadBrowse(IntPtr paramsBuf, uint paramsLen) =>
            MessagePackSerializer.Deserialize<BrowseParams>(CopyParams(paramsBuf, paramsLen), MsgPackOptions);

        private SearchSource Source() => SearchSourceHelper.GetSearchSource(_userSettings);

        private byte[] SerializeGenreSearch(IntPtr paramsBuf, uint paramsLen)
        {
            var p = ReadQuery(paramsBuf, paramsLen);
            var dto = new GenreListResponse { genres = ToGenreList(_library.SearchGenres(p.query ?? string.Empty, Source())) };
            return MessagePackSerializer.Serialize(dto, MsgPackOptions);
        }

        private byte[] SerializeArtistSearch(IntPtr paramsBuf, uint paramsLen)
        {
            var p = ReadQuery(paramsBuf, paramsLen);
            var dto = new ArtistListResponse { artists = ToArtistList(_library.SearchArtists(p.query ?? string.Empty, Source())) };
            return MessagePackSerializer.Serialize(dto, MsgPackOptions);
        }

        private byte[] SerializeAlbumSearch(IntPtr paramsBuf, uint paramsLen)
        {
            var p = ReadQuery(paramsBuf, paramsLen);
            var dto = new AlbumListResponse { albums = ToAlbumList(_library.SearchAlbums(p.query ?? string.Empty, Source())) };
            return MessagePackSerializer.Serialize(dto, MsgPackOptions);
        }

        private byte[] SerializeTrackSearch(IntPtr paramsBuf, uint paramsLen)
        {
            var p = ReadQuery(paramsBuf, paramsLen);
            var dto = new TrackListResponse { tracks = ToTrackList(_library.SearchTracks(p.query ?? string.Empty, Source())) };
            return MessagePackSerializer.Serialize(dto, MsgPackOptions);
        }

        private byte[] SerializeGenreBrowse(IntPtr paramsBuf, uint paramsLen)
        {
            var p = ReadBrowse(paramsBuf, paramsLen);
            var dto = new GenreListResponse { genres = ToGenreList(_library.BrowseGenres(p.offset, p.limit)) };
            return MessagePackSerializer.Serialize(dto, MsgPackOptions);
        }

        private byte[] SerializeArtistBrowse(IntPtr paramsBuf, uint paramsLen)
        {
            var p = ReadBrowse(paramsBuf, paramsLen);
            var dto = new ArtistListResponse { artists = ToArtistList(_library.BrowseArtists(p.offset, p.limit, p.album_artists)) };
            return MessagePackSerializer.Serialize(dto, MsgPackOptions);
        }

        private byte[] SerializeAlbumBrowse(IntPtr paramsBuf, uint paramsLen)
        {
            var p = ReadBrowse(paramsBuf, paramsLen);
            var dto = new AlbumListResponse { albums = ToAlbumList(_library.BrowseAlbums(p.offset, p.limit)) };
            return MessagePackSerializer.Serialize(dto, MsgPackOptions);
        }

        private byte[] SerializeTrackBrowse(IntPtr paramsBuf, uint paramsLen)
        {
            var p = ReadBrowse(paramsBuf, paramsLen);
            var dto = new TrackListResponse { tracks = ToTrackList(_library.BrowseTracks(p.offset, p.limit)) };
            return MessagePackSerializer.Serialize(dto, MsgPackOptions);
        }

        private byte[] SerializeGenreArtists(IntPtr paramsBuf, uint paramsLen)
        {
            var p = ReadQuery(paramsBuf, paramsLen);
            var dto = new ArtistListResponse { artists = ToArtistList(_library.GetGenreArtists(p.query ?? string.Empty, Source())) };
            return MessagePackSerializer.Serialize(dto, MsgPackOptions);
        }

        private byte[] SerializeArtistAlbums(IntPtr paramsBuf, uint paramsLen)
        {
            var p = ReadQuery(paramsBuf, paramsLen);
            var dto = new AlbumListResponse { albums = ToAlbumList(_library.GetArtistAlbums(p.query ?? string.Empty, Source())) };
            return MessagePackSerializer.Serialize(dto, MsgPackOptions);
        }

        private byte[] SerializeAlbumTracks(IntPtr paramsBuf, uint paramsLen)
        {
            var p = ReadQuery(paramsBuf, paramsLen);
            var dto = new TrackListResponse { tracks = ToTrackList(_library.GetAlbumTracks(p.query ?? string.Empty, Source())) };
            return MessagePackSerializer.Serialize(dto, MsgPackOptions);
        }

        private byte[] SerializeNowPlayingDetails()
        {
            var d = _track.GetNowPlayingTrackDetails();
            var dto = new NowPlayingDetailsResponse
            {
                albumArtist = d?.AlbumArtist ?? string.Empty,
                genre = d?.Genre ?? string.Empty,
                trackNo = d?.TrackNo ?? string.Empty,
                trackCount = d?.TrackCount ?? string.Empty,
                discNo = d?.DiscNo ?? string.Empty,
                discCount = d?.DiscCount ?? string.Empty,
                publisher = d?.Publisher ?? string.Empty,
                composer = d?.Composer ?? string.Empty,
                comment = d?.Comment ?? string.Empty,
                grouping = d?.Grouping ?? string.Empty,
                ratingAlbum = d?.RatingAlbum ?? string.Empty,
                encoder = d?.Encoder ?? string.Empty,
                kind = d?.Kind ?? string.Empty,
                format = d?.Format ?? string.Empty,
                size = d?.Size ?? string.Empty,
                channels = d?.Channels ?? string.Empty,
                sampleRate = d?.SampleRate ?? string.Empty,
                bitrate = d?.Bitrate ?? string.Empty,
                dateModified = d?.DateModified ?? string.Empty,
                dateAdded = d?.DateAdded ?? string.Empty,
                lastPlayed = d?.LastPlayed ?? string.Empty,
                playCount = d?.PlayCount ?? string.Empty,
                skipCount = d?.SkipCount ?? string.Empty,
                duration = d?.Duration ?? string.Empty,
            };
            return MessagePackSerializer.Serialize(dto, MsgPackOptions);
        }

        private byte[] SerializeAlbumCover(IntPtr paramsBuf, uint paramsLen)
        {
            var p = MessagePackSerializer.Deserialize<AlbumCoverParams>(
                CopyParams(paramsBuf, paramsLen), MsgPackOptions);
            var payload = _coverService.GetAlbumCover(
                p.artist ?? string.Empty,
                p.album ?? string.Empty,
                string.IsNullOrEmpty(p.client_hash) ? null : p.client_hash);
            var dto = new AlbumCoverResponse
            {
                album = payload?.Album ?? string.Empty,
                artist = payload?.Artist ?? string.Empty,
                cover = payload?.Cover ?? string.Empty,
                status = payload?.Status ?? 404,
                hash = payload?.Hash ?? string.Empty,
            };
            return MessagePackSerializer.Serialize(dto, MsgPackOptions);
        }

        private byte[] SerializeCoverCacheBuildStatus()
        {
            var dto = new CoverCacheBuildStatusResponse { building = _coverService.IsBuildingCache };
            return MessagePackSerializer.Serialize(dto, MsgPackOptions);
        }

        private byte[] SerializeAlbumCoverBatch(IntPtr paramsBuf, uint paramsLen)
        {
            var p = MessagePackSerializer.Deserialize<PaginationParams>(
                CopyParams(paramsBuf, paramsLen), MsgPackOptions);
            var page = _coverService.GetAlbumCoverBatch(p.offset, p.limit);
            var dto = new AlbumCoverBatchResponse
            {
                data = (page?.Data ?? new System.Collections.Generic.List<MusicBeePlugin.Models.Responses.AlbumCoverBatchEntry>())
                    .Select(e => new AlbumCoverBatchEntry
                    {
                        album = e.Album ?? string.Empty,
                        artist = e.Artist ?? string.Empty,
                        cover = e.Cover ?? string.Empty,
                        hash = e.Hash ?? string.Empty,
                        status = e.Status,
                    })
                    .ToList(),
                offset = page?.Offset ?? p.offset,
                limit = page?.Limit ?? p.limit,
                total = page?.Total ?? 0,
            };
            return MessagePackSerializer.Serialize(dto, MsgPackOptions);
        }

        private byte[] SerializePlaybackPosition()
        {
            var pos = _track.GetPlaybackPosition();
            var dto = new PlaybackPositionResponse
            {
                current = pos?.Current ?? 0,
                total = pos?.Total ?? 0,
            };
            return MessagePackSerializer.Serialize(dto, MsgPackOptions);
        }

        #endregion

        /// <summary>
        ///     Pre-loads mbrc_core.dll from the same directory as the plugin assembly.
        /// </summary>
        private void PreloadNativeLibrary()
        {
            var assemblyDir = Path.GetDirectoryName(
                Assembly.GetExecutingAssembly().Location);

            if (assemblyDir == null)
            {
                Logger.Warn("Could not determine assembly directory for native library preload");
                return;
            }

            var dllPath = Path.Combine(assemblyDir, "mbrc_core.dll");

            if (!File.Exists(dllPath))
            {
                Logger.Warn("mbrc_core.dll not found at {0}", dllPath);
                return;
            }

            _libraryHandle = LoadLibrary(dllPath);

            if (_libraryHandle == IntPtr.Zero)
            {
                var errorCode = Marshal.GetLastWin32Error();
                Logger.LogError("Failed to pre-load mbrc_core.dll (Win32 error: {0})", errorCode);
            }
            else
            {
                Logger.Info("Pre-loaded mbrc_core.dll from {0}", dllPath);
            }
        }
    }
}
